[package]
  name = "snappy_image_diff"
  version = "0.1.0"
  authors = []
  edition = "2021"

[lib]
  name = "snappy_image_diff"
  path = "src/lib.rs"
  crate-type = ["cdylib"]

[dependencies]
  rustler = "0.33.0"
  image = "0.25.1"
  image-compare = "0.4.1"
